### ISSUE TITLE
Failure to load 3d files

### ISSUE THREAD

**Issue by wookey** [aardgoose/CaveView.js#12]
Thanks for the great library.  (We have used it in http://expo.survex.com/1623/107.htm)

The attached file unfortunately does not load.
[107.3d.zip](https://github.com/aardgoose/CaveView.js/files/1913020/107.3d.zip)

We have made a small change to the code, which allowed it to work.  Although I am not sure this is not the best approach.

The new line was "if ( station === undefined ) continue; // ADDED LINE OF CODE", as shown in the code below.

Routes.prototype.mapSurvey = function ( stations, legs, surveyTree ) {

	// determine segments between junctions and entrances/passage ends and create mapping array.
	this.surveyTree = surveyTree;

	var segmentMap = this.segmentMap;
	var newSegment = true;

	var station;

	var segment = 0;
	var vertexPairToSegment = this.vertexPairToSegment;
	var segmentToInfo = this.segmentToInfo;

	var v1, v2;

	var i, l = legs.length;

	var segmentInfo;

	for ( i = 0; i < l; i = i + 2 ) {

		v1 = legs[ i ];
		v2 = legs[ i + 1 ];

		vertexPairToSegment.push( segment );

		if ( newSegment ) {

			station = stations.getStation( v1 );
			if ( station === undefined ) continue; // possible use of separator in station name.

			segmentInfo = {
				segment: segment,
				startStation: station,
				endStation: null
			};

			station.linkedSegments.push( segment );

			newSegment = false;

		}

		station = stations.getStation(if ( station === undefined ) continue; // ADDED LINE OF CODE v2 );
		if ( station === undefined ) continue; // ADDED LINE OF CODE
		if ( ( station && station.hitCount > 2 ) || ( i + 2 < l && ! v2.equals( legs[ i + 2 ] ) ) ) {

			// we have found a junction or a passage end
			segmentInfo.endStation = station;

			segmentMap.set( segmentInfo.startStation.id + ':' + station.id, segmentInfo );
			segmentToInfo[ segment ] = segmentInfo;

			station.linkedSegments.push( segment );

			segment++;

			newSegment = true;

		}

	}

	if ( ! newSegment ) {

		segmentInfo.endStation = station;

		segmentMap.set( segmentInfo.startStation.id + ':' + station.id, segmentInfo );

		station.linkedSegments.push( segment );

	}

	return this;

};

**Comment by aardgoose** [comment]
Hi,

I must have encountered this problem myself because its fixed in the current version,  Try using the full demo at https://aardgoose.github.io/CaveView.js/fulldemo.html. You can drag n drop your own surveys onto the view for a quick test. Your file works for me there.

Incidentally, would you be interested in creating a set of terrain tiles for your expo caves.  Iv'e noticed that there is a freely available 10m res DTM available for Austria, and if the .3d files can be created with a CRS speciified, a terrain can be applied with other imagery overlays etc. 


Regards

**Comment by wookey** [comment]
On 2018-04-16 02:12 -0700, aardgoose wrote:
> Hi,
> 
> I must have encountered this problem myself because its fixed in the current
> version, Try using the full demo at https://aardgoose.github.io/CaveView.js/
> fulldemo.html. You can drag n drop your own surveys onto the view for a quick
> test. Your file works for me there.

OK cool. We use the last release (1.2.2), but not 'latest git'.

I plan to package CaveView for debian, now I've noticed how useful it is :-)

One query: does it have a 'keep Z up' option somewhere? For caves it's
really handy if up stays up, at least by default.

> Incidentally, would you be interested in creating a set of terrain tiles for
> your expo caves. I've noticed that there is a freely available 10m res DTM
> available for Austria, and if the .3d files can be created with a CRS
> speciified, a terrain can be applied with other imagery overlays etc.

We already have some terrain files, that we use in survex. And we've
got some higher-res (1m) data last year, but we can't redistribute
that.  These are the public ones, from aster, STRM and some
flight-simulator people http://expo.survex.com/expofiles/terrain/

I wanted to work out what formats caveview takes and see about making that work, so yes.
What's a CRS specification?

Wookey
-- 
Principal hats:  Linaro, Debian, Wookware, ARM
http://wookware.org/

**Comment by aardgoose** [comment]
Hi

1.7 has a few more things like shading by distance from a selected station and greatly reduced memory use (a mixture of major code improvements and some changes I've pushed to three.js), and most display colours etc are theme-able.  Limiting the display to Z up should be quite simple to add, feature suggestions always welcome,
 
Re Terrain files, the files are basically 16 bit integer grids (16 bit to keep the size down without too much loss of accuracy).  I create the files using the GRASS GIS package which I see is available in Debian. If you can provide an example .3d  model with the *CS specified I will work through and document the process required to make terrain tiles. 

CRS = Coordinate Reference System ( *CS in Survex ) - The javascript proj4j library doesn't contain all the 
name to parameter lookups that the 'C' version has so I need to sort a way out to deal with that, currently I've hard coded OS GB but obviously not any use outside UK.

Angus

**Comment by aardgoose** [comment]
Hi @wookey 

1.8 now available.  This limits the z axis to 90 degrees from vertical so you can 't see the model from below by default now. I've also fixed a bug where the LRUD passage walls were missing in places from your model.

**Comment by ojwb** [comment]
> This limits the z axis to 90 degrees from vertical so you can 't see the model from below by default now.

That seems a rather annoying limitation, and I don't think it is what Wookey was suggesting at all (both aven and loch allow viewing from below after all).

I think he was saying that "up" in the virtual world should always be up the screen (except in the extreme cases of plan view and viewing from below when virtual "up" is out of/into the screen).  So the camera should be able to pitch and yaw but not roll, and also it shouldn't be possible to go past 90° or -90° so the cave ends up upside-down to the viewer.  I'm not sure how he was getting CaveView to do either of these though - I can't see to make it happen.

**Comment by aardgoose** [comment]
@ojwb 

You are correct that the controls don't allow roll (it uses the OrbitController from the Three.js examples) or over rorat, hence my interpretation of his request.  @wookey can you clarify?

This is a config option so it would be simple to revert to the original behaviour, and still allow this constraint if it is what is required.

**Comment by wookey** [comment]
On 2018-06-29 13:40 +0000, aardgoose wrote:
> @ojwb
> 
> You are correct that the controls don't allow roll (it uses the OrbitController
> from the Three.js examples) or over rorat, hence my interpretation of his
> request. @wookey can you clarify?

What I was wanting is to be able to rotate the cave with vertical
staying up the screen. It's currently very difficult to do. i.e to yaw
without pitching. Equally pitching without yawing is also useful
sometimes. But always having both on one control makes it very hard to drive.

Aven separates these controls, and so does loch.
Loch and aven both have: 
* zoom and rotate (yaw) on one control
* tilt (pitch) on another control
* pan on a 3rd control

I think this works way better than cavewview's 
* rotate (yaw) and tilt (pitch) on one control
* zoom on another control
* pan on a 3rd control

So essentially what I am asking is 'please make the controls work like
aven and loch'.

If three.js makes that difficult to implement, can we perhaps have a
modifier key to allow pitch, but by default you only get yaw? Or it
could switch between pitch-only and yaw-only? Not sure what's
best. Just that as it stands it's extremely difficult to rotate the
cave whilst keeping up up (which is IMHO what people normally want to
do).  At a pinch I guess just less sensitivity in pitch would help.

Wookey
-- 
Principal hats:  Linaro, Debian, Wookware, ARM
http://wookware.org/

**Comment by aardgoose** [comment]
Thanks for the clarification, it's not a mode supported by Three.js off the shelf, but nothing should stop it being implemented.  I'll take a look.

**Comment by ojwb** [comment]
Aven actually handles the zoom and rotate (left button drag) in a slightly magic way - roughly speaking, if the position is "close" to screen-XY axes from the start point of the drag it only zooms (if close to the Y axis) or only rotates (if close to the X axis).  This allows zooming and rotating independently, and I doubt most users even realise anything special is happening.  The code is in `src/guicontrol.cc` in method `GUIControl::HandleScaleRotate(wxPoint point)`.

Therion doesn't seem to do this, and if you compare trying to only zoom with a left button drag in aven and loch one after the other you can clearly see the difference.

BTW Aven implements CaveView-style left drag if you hold down Ctrl while you left drag, which might be useful for comparing how they feel (this mode doesn't have the "magic axes").

**Comment by aardgoose** [comment]
@wookey 

Can you try this: https://aardgoose.github.io/CaveView.js/test.html

(it should be quite close to survex's controls (I've followed the code referred to above quite closely) , lightly tested).

**Comment by ojwb** [comment]
Yeah, that seems to work very nicely.

**Comment by ojwb** [comment]
I think this issue can be closed now.

**Comment by aardgoose** [comment]
Thanks.
