### ISSUE TITLE
loadCaveList with wildcards

### ISSUE THREAD

**Issue by vldgeorgiev** [aardgoose/CaveView.js#2]
Hi
Is it possible to make the loadCaveList function use wildcards for the cave model names? E.g. *.lox;*.3d, etc.
Currently it seems to require listing each file manually, which is OK, but for example I might have a build script that exports a new cave's model and uploads it to the FTP folder without the need to update the html file.

**Comment by aardgoose** [comment]
Hi,

apologies for delay, unfortunately http doesn't provide directory lookup functions, so there is no way of doing this without server side help, for example Apache 'Options +Indexes' feature.

If you have this enabled on a server, I could write something that parses the server generated index and then creates the object to pass loadCaveList(), however this would be web server specific and web server configuration specific.

**Comment by vldgeorgiev** [comment]
Hi
Yes, you are right, I was thinking of some indexing of the files in the folder. But now that you mentioned it, it will require htaccess changes. My server is on a shared hosting and I suppose they might not like such options.
So it was just wishful thinking, never mind :)
