### ISSUE TITLE
.git pack file too large

### ISSUE THREAD

**Issue by goatchurchprime** [aardgoose/CaveView.js#22]
I'm running out of memory on my computer and was searching for some big files when I found the at the CaveView.js/.git/objects/pack/*.pack file is 420Mb large

On trying out a script included in the link, it seems that you've committed and then deleted the terrain files for the entire world!  
https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history

Is there a way to clean them out properly so that I'm not losing so much memory by having a copy of this project?

**Comment by aardgoose** [comment]
Well spotted!
The terrain was a previous incarnation for Derbyshire in OSGB36.
I have done some history editing on the repo and removed that and some other large files, the whole repo is now about 54M, mostly the pack file, which should be more manageable.

If you do a new clone this should be sorted.

**Comment by goatchurchprime** [comment]
54Mb still seems a bit excessive for something that ought not to have any binaries, but I'll accept this 87% improvement.
