### ISSUE TITLE
Drag and drop .3d files onto window

### ISSUE THREAD

**Issue by goatchurchprime** [aardgoose/CaveView.js#28]
I hadn't realized you were crazy enough to implement a .3d parser in pure javascript!  

My groundwindow implementation required a preprocessing of dump3d output of a 3d file into a json object.

Since you have this capability, you might as well allow for convenient drag-and-dropping of 3d files into the window, so we can fully replace the aven viewer.    

Here's the code that enabled this in another project I did:
    https://bitbucket.org/goatchurch/laserplacer/src/3c22291edfd2b0d7a6dc1ae68369cfcadc539eed/viewcontrols.js#lines-108

**Comment by aardgoose** [comment]
You already can do d'n'd.  Actually you can drag and drop a set of files together and they will be combined presuming they occupy the same geographical space (someone asked for this!).

Re parsing. I started using the survex json export which sadly isn't geojson and then KML, but both loose a lot of information, I was nicely surprised how fast javascript could be, Therion lox parsing was simpler to write but the format isn't documented.

**Comment by goatchurchprime** [comment]
My bad.  When I tried it myself it didn't work first time.
