### ISSUE TITLE
CSS overriding global styles

### ISSUE THREAD

**Issue by MaticDiba** [aardgoose/CaveView.js#38]
Hi,
I noticed there is one styles definiton in the CaveView css file which is overriding my global styles. It's quite "loosley" defined, so maybe this could be changed. I'm not sure for which part of the widget this definition is actually used.

This is the styles definition:
```
li span {
  display: inline-block;
  width: 10px;
  padding-right: 2px;
}
```

**Comment by aardgoose** [comment]
Yes, that is a bit loose. It will be used in the survey structure tree I suspect, a while since I looked at that bit.

I'll fix that.

**Comment by aardgoose** [comment]
This is fixed in the latest release.
Thanks
