### ISSUE TITLE
Feature request - Terrain shading : depth from surface

### ISSUE THREAD

**Issue by speleo** [aardgoose/CaveView.js#39]
The depth from surface can be viewed by clicking on data points.  

Would it be possible to have an option to shade by depth from surface?  This would be an extremely usefull tool.

**Comment by aardgoose** [comment]
Hi,

It already has! (keyboard shortcut '8' or its 'depth' in the underground leg shading dropdown menu item)

The accuracy is limited by the fact the depth is obtained from a 1024 x 1024 depth map over the area of the survey, but good enough for visualisation I would imagine.

The  Peak Cavern/Speedwell survey illustrates it well, with the horizontal Speedwell canal:

https://peakdistrictcaving.info/home/the-caves/castleton/model

**Comment by speleo** [comment]
Very good indeed.  Just seen the depth cursor too.  Amazing tool.

Thank you, Henry
