### ISSUE TITLE
CaveView.js file does not exist

### ISSUE THREAD

**Issue by speleo** [aardgoose/CaveView.js#4]
Install instructions refers to CaveView.js which does not exist.

> **CaveView.js**
> 
> The CaveView application is provided in one javascript file. Include this in the body section of the page.
> 
> 	<script type="text/javascript" src="%path%/CaveView/js/CaveView.js" ></script>

**Comment by aardgoose** [comment]
Fixed (not pushed from my local copy, because of .gitignore entry)

Thanks!

**Comment by speleo** [comment]
working now.  Thanks!
