### ISSUE TITLE
Translation - missed strings

### ISSUE THREAD

**Issue by damjang** [aardgoose/CaveView.js#40]
Hi there! I'm translating CaveView to slovenian and italian language, but find that some strings are not translatable. Can they be added?
The needed strings are:
- "intro" in Edit
- "Start" and "End" in Edit mode - Traces
- "file" in Survey Stats
- "A WebGL 3d   cave viewer for Survex (.3d), Therion (.lox) and Compass (.plt) models.", "For more information see:" and "CaveView on GitHub" in Information

Thank you!

**Comment by aardgoose** [comment]
Hi,
I've added the strings you have mentioned. I'll make a new release soon.
Thanks

**Comment by damjang** [comment]
Thank you!
I want also to remember to copy the src/js/core/defaultLanguage.json to build/CaveView/lib/lang-template.json that is not updated now.

**Comment by damjang** [comment]
Thank you for new version. When translating I find that maybe there is a wrong word used for HEIGHT indicator. Maybe will be better to use DEPTH instead HEIGHT word? But maybe I'm wrong? I see that "depth" string is already present in translation strings. There is also the same word used 2 times in Settings->Shading->Underground legs selection menu.

**Comment by aardgoose** [comment]
I use height for height above the coordinate system datum (height above sea level etc). 
I use depth for depth below the surface when a terrain model (DTM) is present.
