### ISSUE TITLE
Measuring distance/denivelation between 2 stations?

### ISSUE THREAD

**Issue by robertxa** [aardgoose/CaveView.js#48]
Hi,

This is not an issue, only a suggestion, as I am often asked about that: Is there a possibility to implement a way to measure a distance (d and dx, dy, dz) between 2 stations that do not belong to the same cave? The idea is to get a sense on how long do we have sometimes to dig and/or climb to connect to caves !

That would be great !

Cheers,

Xavier
(Thanks a lot for Caveview, this is really useful!)

**Comment by aardgoose** [comment]
Hi,

The demo site https://aardgoose.github.io/CaveView.js/ has a first go at implementing distance between two stations.

To use hold down "shift" and click on a station to select the starting point, you can now then move the mouse over other stations to find the distance between the stations and the dx/dy/dz offsets.

Let me know if this is a useable UI.

Cheers

**Comment by robertxa** [comment]
Hi,

Wow ! Super, this is exactly what I was looking for ! At first use, it seems that the UI is well usable !  That's great !
Thanks a lot !

I think that this "issue" can be closed now !

Cheers,

Xavier
