### ISSUE TITLE
defaultLanguage.json problem

### ISSUE THREAD

**Issue by damjang** [aardgoose/CaveView.js#52]
I think that there are some problems with /CaveView.js/blob/dev/src/js/core/defaultLanguage.json e.g. there was removed the Colours section, also if this sections remains in Settings. Maybe there are some other string removed by error?
Please update (sync) also the same file in /CaveView.js/blob/dev/build/CaveView/lib/lang-template.json

**Comment by aardgoose** [comment]
Hi, 
I can't see anything missing, the 'colors' settings are all present in both copies, and there is only an ordering difference between the two copies.  Can you double check you have the latest copies of both files?

**Comment by damjang** [comment]
Ops, you're right. I recheck again and all seems ok. I don't know from where I copy the wrong file... sorry!
