### ISSUE TITLE
Terrain Map Overlay geo cropping

### ISSUE THREAD

**Issue by speleo** [aardgoose/CaveView.js#6]
when displaying a terrain map overlay from a lox file the display doesn't crop the image and locate correctly.  For example take a look at  this file
http://bec-cave.org.uk/Philippines/build/surveys/BlueWater-System.lox

When viewed in Loch the survey is shown in the correct reference to the overlaying terrain.  However in CaveView it shows the complete image file for the whole area.  Loch seems to crop the terrain file to just the area being viewed.  CaveView takes the whole image file but doesn't crop it.  

Best way is to take a look in Loch and CaveView and you'll see what I mean.

Really liking your project.  This is the best think I've seen for some time.  Congrats!!!

**Comment by aardgoose** [comment]
Hi, thanks,

I see the issue. .

 .lox files haven't been my main focus mainly because I don't have many examples to test, so thanks for the info.  Next on my list of things to fix.

**Comment by speleo** [comment]
1.2.1 is perfect.  Thanks!

**Comment by aardgoose** [comment]
Cheers,

Lox terrain & overlay was my first attempt at terrain rendering, it was a bit of a bodge, was just learning 3d graphics. 

The .lox format appears to allow multiple overlay images, do you know of any examples of this in the wild?
