### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Shemesh** [aardgoose/CaveView.js#62]
hi @aardgoose 
i'm trying to build latest code from branch "dev".
got node v20.1.0
cloned the repo, ran "npm i"
when running npm build it fails on:
RollupError: "Line2NodeMaterial" is not exported by "src/js/Nodes.js", imported by "src/js/core/LineSegments2.js".

seems "Line2NodeMaterial" is expected to come from "node_modules/three/examples/jsm/nodes/Nodes"
but it does not exist there. my 'three' version is 0.156.1

what am i missing?

**Comment by Shemesh** [comment]
@aardgoose seems like you work with "three" code that is not released?
the missing code is in "three" dev branch only?

**Comment by Shemesh** [comment]
yes, as suspected...
i have pointed "three" to "mrdoob/three.js#dev" and it works.

**Comment by aardgoose** [comment]
Hi,

The dev branch is/was work in progress (by accident). I have rolled it back to the last release version which should build with the specified version of Three.js.  

I have moved the very much experimental code to the v3 branch, which is intended to work with the experimental WebGPU renderer (which will also fall back to WebGL as required).
