### ISSUE TITLE
Cannot visualise .3d in EPSG:27700

### ISSUE THREAD

**Issue by aricooperdavis** [aardgoose/CaveView.js#67]
I am trying to visualise [a .3d file that uses a station fixed in EPSG:27700](https://github.com/aricooperdavis/wheal-pell/releases/download/v0.0.3/pell.3d).

When I load it into CaveView I get the following console messages:

```
CaveView v2.7.3
Survex .3d version  v8
looking up CRS code EPSG: 27700
Reprojecting from +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +nadgrids=OSTN15_NTv2_OSGBtoETRS.gsb +units=m +no_defs +type=crs to EPSG:3857
Unable to find mandatory grid 'OSTN15_NTv2_OSGBtoETRS.gsb'
```

This results in pop-up `alert()`:

```
Failed loading cave information: TypeError: point is undefined.
```

**Comment by aricooperdavis** [comment]
This is probably a limitation in using [proj4js with grid based datums](https://github.com/proj4js/proj4js?tab=readme-ov-file#grid-based-datum-adjustments) like EPSG:27700?

**Comment by aardgoose** [comment]
Ari,  Forgot to say, the latest version should work, it will be happy if adjustment grids aren't available now (positions will be slightly shifted but locations are correct within a few metres without the UK grid file in any case. If you do want to use grid files, they should be placed in the same directory as the survey file(s).
