### ISSUE TITLE
Left panel dissapears on tileSets.json load fail

### ISSUE THREAD

**Issue by apgeo** [aardgoose/CaveView.js#9]
When you change the model (select another in the dropdown box),
if the tileSets.json file cannot be found on the server,
the left panel gets hidden (along with the small control buttons that are used to show it back) and there seems to be no way to display the panel or the small control buttons again.

The cause seems to be the tileSets.json file when it cannot be found on the server. If you place an empty tileSets.json file (and configure the terrainDirectory parameter to the files directory), the problem is avoided.

Test environment:
1. Google Chrome | 60.0.3112.90 (Official Build) (64-bit)
2. Firefox 54.0.1 (64-bit)
Windows 7 64-bit

**Comment by aardgoose** [comment]
A failure mode I haven't tested for, I'll fix that soon.
Thanks.

**Comment by aardgoose** [comment]
Fixed with 1.2.2
